# Generated by Django 3.0.8 on 2020-10-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201012_2025'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_products',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collectionproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collecting',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionProduct',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
