# Generated by Django 3.0.6 on 2020-10-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201025_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detail_address',
            field=models.CharField(default='상세주소', max_length=300, verbose_name='상세주소'),
            preserve_default=False,
        ),
    ]
