# Generated by Django 3.0.8 on 2020-10-12 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.PositiveIntegerField(verbose_name='총 가격')),
                ('address', models.CharField(max_length=300, verbose_name='배송지 주소')),
                ('collection_name', models.CharField(max_length=100, verbose_name='컬렉션명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Collection', verbose_name='컬렉션')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문상품',
                'verbose_name_plural': '주문상품',
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='주문')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderProduct', verbose_name='주문 상품')),
            ],
            options={
                'unique_together': {('order', 'order_product')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(related_name='order_products', through='orders.Ordering', to='orders.OrderProduct', verbose_name='주문상품'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
