# Generated by Django 3.0.6 on 2020-10-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201020_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_message',
            field=models.TextField(blank=True, verbose_name='배송 요청사항'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(default='이주영', max_length=10, verbose_name='받는 사람'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(default='010-7255-3753', max_length=15, verbose_name='수령인 연락처'),
            preserve_default=False,
        ),
    ]
