# Generated by Django 3.0.6 on 2020-10-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201025_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isValid',
            field=models.BooleanField(default=True, verbose_name='유효성'),
        ),
        migrations.AddField(
            model_name='order',
            name='period',
            field=models.CharField(choices=[('1W', '1주'), ('2W', '2주'), ('3W', '3주'), ('1M', '1달'), ('2M', '2달'), ('3M', '3달')], default='1W', max_length=2, verbose_name='주기'),
            preserve_default=False,
        ),
    ]
