# Generated by Django 3.0.8 on 2020-10-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드명')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='상품가격')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='상품이미지')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, '스킨케어'), (1, '메이크업'), (2, '헤어케어'), (3, '바디케어'), (4, '향수/방향'), (5, '리빙/잡화'), (6, '맨케어'), (7, '헬스'), (8, '푸드'), (9, '베이비케어'), (10, '펫케어')], verbose_name='상품종류')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
